### ISSUE TITLE
Doesn't work on Arch Linux

### ISSUE THREAD

**Issue by robotTX1** [threadexio/Legion-Y720-Keyboard-Backlight#2]
Dear threadexio,

I installed your software on Arch Linux and it doesn't work.
I tried to install it with AUR and did it manually as well, unfortunately neither of them worked.
I tried to load the default profile to test it and it logs: "  ✔  Loaded profile: default" but the lights doesn't turn on.
Running with sudo didn't help.

The other tool works but I really don't need a GUI.

**Comment by threadexio** [comment]
Thank you for reporting this. I believe the problem is due to a change in the kernel, but I'm not sure, I will have to look into it more.

**Comment by threadexio** [comment]
The issue was, in fact, related to a kernel change. But it is now resolved in release [2.0.2](https://github.com/threadexio/Legion-Y720-Keyboard-Backlight/releases/tag/2.0.2). All your previous config files should be compatible with this new release.

**Comment by threadexio** [comment]
The latest release ([2.0.2](https://github.com/threadexio/Legion-Y720-Keyboard-Backlight/releases/tag/2.0.2)) should have fixed the problem you described. It should also be backwards compatible with all your previous configuration files.

**Comment by robotTX1** [comment]
It's working! Thanks for the fast fix!
